### ISSUE TITLE
Instructions for Building

### ISSUE THREAD

**Issue by UberPilot** [DRE2N/CaliburnAPI#6]
Hey, I was interested in helping to add support for 1.15. Could we get some instructions for building this added to the main page? Right now I'm struggling to get some of the dependencies needed to build the project.

**Comment by Sataniel98** [comment]
Hey,
building should work as it is with Maven, but this library works well with 1.15.
The https://github.com/DRE2N/CaliburnAPI/tree/1.0 branch contains the latest changes.
